host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: centos:7
    operating_system: 
      name: centos
      version: "7"
    python_version: "3.6"
    recommendation_type: latest
