apiVersion: v1
kind: Template
metadata:
  name: adviser
  annotations:
    description: "Thoth: Adviser"
    openshift.io/display-name: "Thoth: Adviser"
    version: 0.6.3
    tags: thoth,ai-stacks,adviser
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run recommendation logic of Thoth to OpenShift.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    app: thoth
    template: adviser
    component: adviser

parameters:
  - name: THOTH_ADVISER_JOB_ID
    required: true
    description: A unique dentifier of adviser job.
    displayName: Adviser id
  - name: THOTH_ADVISER_REQUIREMENTS
    required: false
    description: Raw stack requirements
  - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
    required: false
    description: Fully pinned down stack
    displayName: Locked requirements
  - name: THOTH_ADVISER_LIBRARY_USAGE
    required: false
    description: Usage of libraries for adviser's resolution algorithm.
    displayName: Library usage
  - name: THOTH_ADVISER_REQUIREMENTS_FORMAT
    required: false
    description: Format of input
    displayName: Requirements format
  - name: THOTH_ADVISER_RECOMMENDATION_TYPE
    required: false
    description: Type of requested recommendation
    displayName: Recommendation type
  - name: THOTH_ADVISER_RUNTIME_ENVIRONMENT
    required: false
    description: Runtime environment to create recommendation for
    displayName: Runtime environment
  - name: THOTH_ADVISER_METADATA
    required: false
    description: Metadata carried with the adviser request
    displayName: Adviser metadata
  - name: THOTH_ADVISER_SEED
    required: true
    description: Random seed to run adviser with.
    displayName: Random seed
    # Keep seed constant across adviser runs so that two runs with same knowledge base report same results to user.
    # Not to answer with a different stack each time a request is made.
    value: "42"
  - name: THOTH_ADVISER_BEAM_WIDTH
    required: true
    description: Adviser's beam width to restrict memory requirements with states generated.
    displayName: Beam width
    value: "100000"
  - name: THOTH_LOG_ADVISER
    required: false
    description: Log adviser actions
    displayName: Log adviser actions
    value: INFO
  - name: THOTH_ADVISER_LIMIT
    required: false
    description: Limit number of software stacks scored.
    displayName: Adviser limit.
    value: "100000"
  - name: THOTH_ADVISER_COUNT
    required: false
    description: Number of software stacks returned in the recommendation.
    displayName: Adviser count.
    value: "1"
  - name: THOTH_ADVISER_LIMIT_LATEST_VERSIONS
    required: false
    description: Limit number of versions starting from latest in stacks.
    displayName: Limit latest versions.
    value: "9999999"
  - name: THOTH_ADVISER_TIMEOUT_SECONDS
    required: true
    description: Give adviser specified number of seconds on CPU to compute results.
    displayName: Adviser timeout seconds.
    value: "1500"
  - name: THOTH_FORCE_SYNC
    description: Perform force sync - sync data even if they are reported to be existing
    displayName: Perform force sync
    required: true
    value: "0"

  - name: IMAGE_STREAM_REGISTRY
    description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    value: "docker-registry.default.svc:5000"
  - name: IMAGE_STREAM_NAMESPACE
    description: Namespace the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    value: "thoth-infra-stage"
  - name: IMAGE_STREAM_TAG
    description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    value: "latest"

objects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      name: "${THOTH_ADVISER_JOB_ID}"
      annotations:
        thoth-station.ninja/template-version: 0.6.3
      labels:
        app: thoth
        component: adviser
    spec:
      serviceAccountName: argo
      ttlStrategy:
        secondsAfterSuccess: 3600  # Keep adviser 1h to let users browse the logs.
        # secondsAfterFailure kept unset to keep failed advisers
      entrypoint: adviser
      arguments:
        parameters:
          - name: THOTH_ADVISER_JOB_ID
            value: "${THOTH_ADVISER_JOB_ID}"
          - name: THOTH_DOCUMENT_ID
            value: "${THOTH_ADVISER_JOB_ID}"
          - name: THOTH_LOG_ADVISER
            value: "${THOTH_LOG_ADVISER}"
          - name: THOTH_ADVISER_TIMEOUT_SECONDS
            value: "${THOTH_ADVISER_TIMEOUT_SECONDS}"
          - name: THOTH_ADVISER_REQUIREMENTS
            value: "${THOTH_ADVISER_REQUIREMENTS}"
          - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
            value: "${THOTH_ADVISER_REQUIREMENTS_LOCKED}"
          - name: THOTH_ADVISER_LIBRARY_USAGE
            value: "${THOTH_ADVISER_LIBRARY_USAGE}"
          - name: THOTH_ADVISER_REQUIREMENTS_FORMAT
            value: "${THOTH_ADVISER_REQUIREMENTS_FORMAT}"
          - name: THOTH_ADVISER_RECOMMENDATION_TYPE
            value: "${THOTH_ADVISER_RECOMMENDATION_TYPE}"
          - name: THOTH_ADVISER_RUNTIME_ENVIRONMENT
            value: "${THOTH_ADVISER_RUNTIME_ENVIRONMENT}"
          - name: THOTH_ADVISER_METADATA
            value: "${THOTH_ADVISER_METADATA}"
          - name: THOTH_ADVISER_SEED
            value: "${THOTH_ADVISER_SEED}"
          - name: THOTH_ADVISER_BEAM_WIDTH
            value: "${THOTH_ADVISER_BEAM_WIDTH}"
          - name: THOTH_ADVISER_LIMIT
            value: "${THOTH_ADVISER_LIMIT}"
          - name: THOTH_ADVISER_COUNT
            value: "${THOTH_ADVISER_COUNT}"
          - name: THOTH_ADVISER_LIMIT_LATEST_VERSIONS
            value: "${THOTH_ADVISER_LIMIT_LATEST_VERSIONS}"
          - name: THOTH_FORCE_SYNC
            value: "${THOTH_FORCE_SYNC}"
          - name: IMAGE_STREAM_REGISTRY
            value: "${IMAGE_STREAM_REGISTRY}"
          - name: IMAGE_STREAM_NAMESPACE
            value: "${IMAGE_STREAM_NAMESPACE}"
          - name: IMAGE_STREAM_TAG
            value: "${IMAGE_STREAM_TAG}"
          - name: ceph_bucket_prefix
          - name: ceph_bucket_name
          - name: ceph_host
          - name: deployment_name

      volumes:
        - name: workdir
          emptyDir: {}
        - name: output
          emptyDir: {}
      templates:
        - name: "adviser"
          archiveLocation:
            archiveLogs: true
          dag:
            tasks:
              - name: "advise"
                templateRef:
                  name: "advise"
                  template: "advise"
                continueOn:
                  failed: true
                arguments:
                  parameters:
                    - name: THOTH_ADVISER_JOB_ID
                      value: "{{workflow.parameters.THOTH_ADVISER_JOB_ID}}"
                    - name: THOTH_DOCUMENT_ID
                      value: "{{workflow.parameters.THOTH_DOCUMENT_ID}}"
                    - name: THOTH_LOG_ADVISER
                      value: "{{workflow.parameters.THOTH_LOG_ADVISER}}"
                    - name: THOTH_ADVISER_REQUIREMENTS
                      value: "{{workflow.parameters.THOTH_ADVISER_REQUIREMENTS}}"
                    - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
                      value: "{{workflow.parameters.THOTH_ADVISER_REQUIREMENTS_LOCKED}}"
                    - name: THOTH_ADVISER_LIBRARY_USAGE
                      value: "{{workflow.parameters.THOTH_ADVISER_LIBRARY_USAGE}}"
                    - name: THOTH_ADVISER_REQUIREMENTS_FORMAT
                      value: "{{workflow.parameters.THOTH_ADVISER_REQUIREMENTS_FORMAT}}"
                    - name: THOTH_ADVISER_RECOMMENDATION_TYPE
                      value: "{{workflow.parameters.THOTH_ADVISER_RECOMMENDATION_TYPE}}"
                    - name: THOTH_ADVISER_RUNTIME_ENVIRONMENT
                      value: "{{workflow.parameters.THOTH_ADVISER_RUNTIME_ENVIRONMENT}}"
                    - name: THOTH_ADVISER_METADATA
                      value: "{{workflow.parameters.THOTH_ADVISER_METADATA}}"
                    - name: THOTH_ADVISER_SEED
                      value: "{{workflow.parameters.THOTH_ADVISER_SEED}}"
                    - name: THOTH_ADVISER_BEAM_WIDTH
                      value: "{{workflow.parameters.THOTH_ADVISER_BEAM_WIDTH}}"
                    - name: THOTH_ADVISER_LIMIT
                      value: "{{workflow.parameters.THOTH_ADVISER_LIMIT}}"
                    - name: THOTH_ADVISER_COUNT
                      value: "{{workflow.parameters.THOTH_ADVISER_COUNT}}"
                    - name: THOTH_ADVISER_LIMIT_LATEST_VERSIONS
                      value: "{{workflow.parameters.THOTH_ADVISER_LIMIT_LATEST_VERSIONS}}"
                    - name: THOTH_ADVISER_TIMEOUT_SECONDS
                      value: "{{workflow.parameters.THOTH_ADVISER_TIMEOUT_SECONDS}}"
                    - name: IMAGE_STREAM_REGISTRY
                      value: "{{workflow.parameters.IMAGE_STREAM_REGISTRY}}"
                    - name: IMAGE_STREAM_NAMESPACE
                      value: "{{workflow.parameters.IMAGE_STREAM_NAMESPACE}}"
                    - name: IMAGE_STREAM_TAG
                      value: "{{workflow.parameters.IMAGE_STREAM_TAG}}"
                    - name: "THOTH_S3_ENDPOINT_URL"
                      value: "{{workflow.parameters.ceph_host}}"
                    - name: "THOTH_CEPH_BUCKET_NAME"
                      value: "{{workflow.parameters.ceph_bucket_name}}"
                    - name: "THOTH_CEPH_BUCKET_PREFIX"
                      value: "{{workflow.parameters.ceph_bucket_prefix}}"
                    - name: "THOTH_DEPLOYMENT_NAME"
                      value: "{{workflow.parameters.deployment_name}}"

              - name: "graph-sync-advise"
                dependencies:
                  - "advise"
                templateRef:
                  name: "graph-sync"
                  template: "graph-sync"
                arguments:
                  artifacts:
                    - name: outputdocument
                      from: "{{tasks.advise.outputs.artifacts.outputdocument}}"
                  parameters:
                    - name: "THOTH_DOCUMENT_ID"
                      value: "{{workflow.parameters.THOTH_DOCUMENT_ID}}"
                    - name: "THOTH_FORCE_SYNC"
                      value: "{{workflow.parameters.THOTH_FORCE_SYNC}}"
                    - name: "IMAGE_STREAM_REGISTRY"
                      value: "{{workflow.parameters.IMAGE_STREAM_REGISTRY}}"
                    - name: "IMAGE_STREAM_NAMESPACE"
                      value: "{{workflow.parameters.IMAGE_STREAM_NAMESPACE}}"
                    - name: "IMAGE_STREAM_TAG"
                      value: "{{workflow.parameters.IMAGE_STREAM_TAG}}"

              - name: "trigger-finished-webhook"
                dependencies:
                  - "advise"
                templateRef:
                  name: "finished-webhook"
                  template: "finished-webhook"
                arguments:
                  parameters:
                    - name: "WORKFLOW_NAME"
                      value: "{{workflow.parameters.THOTH_ADVISER_JOB_ID}}"
                    - name: "THOTH_DOCUMENT_ID"
                      value: "{{workflow.parameters.THOTH_DOCUMENT_ID}}"
                    - name: "THOTH_ADVISER_METADATA"
                      value: "{{workflow.parameters.THOTH_ADVISER_METADATA}}"
