apiVersion: v1
kind: Template
metadata:
  name: adviser
  annotations:
    description: "Thoth: Adviser"
    openshift.io/display-name: "Thoth: Adviser"
    version: 0.4.0
    tags: thoth,ai-stacks,adviser
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run recommendation logic of Thoth to OpenShift.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    app: thoth
    template: adviser
    component: adviser

parameters:
  - description: Project the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

  - name: THOTH_ADVISER_JOB_ID
    required: true
    description: A unique dentifier of adviser job.
    displayName: Adviser id
  - name: THOTH_ADVISER_OUTPUT
    required: false
    description: Remote where results should be send to
  - name: THOTH_ADVISER_REQUIREMENTS
    required: false
    description: Raw stack requirements
  - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
    required: false
    description: Fully pinned down stack
    displayName: Locked requirements
  - name: THOTH_ADVISER_REQUIREMENTS_FORMAT
    required: false
    description: Format of input
    displayName: Requirements format
  - name: THOTH_ADVISER_RECOMMENDATION_TYPE
    required: false
    description: Type of requested recommendation
    displayName: Recommendation type
  - name: THOTH_ADVISER_RUNTIME_ENVIRONMENT
    required: false
    description: Runtime environment to create recommendation for
    displayName: Runtime environment
  - name: THOTH_LOG_ADVISER
    required: false
    description: Log adviser actions
    displayName: Log adviser actions
    value: INFO
  - name: THOTH_ADVISER_LIMIT
    required: false
    description: Limit number of software stacks scored.
    displayName: Adviser limit.
    value: "500"
  - name: THOTH_ADVISER_COUNT
    required: false
    description: Number of software stacks returned in the recommendation.
    displayName: Adviser count.
    value: "1"
  - name: THOTH_ADVISER_LIMIT_LATEST_VERSIONS
    required: false
    description: Limit number of versions starting from latest in stacks.
    displayName: Limit latest versions
  - name: THOTH_ADVISER_TIMEOUT_SECONDS
    required: true
    description: Give adviser specified number of seconds on CPU to compute results.
    displayName: Adviser timeout seconds.
    value: "3600"

objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: ${THOTH_ADVISER_JOB_ID}
      labels:
        app: thoth
        component: adviser
        operator: graph-sync
        task: adviser
        mark: cleanup
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: thoth
            component: adviser
            mark: cleanup
        spec:
          restartPolicy: Never
          automountServiceAccountToken: false
          containers:
            - name: adviser
              image: "${IMAGE_STREAM_NAMESPACE}/adviser:${IMAGE_STREAM_TAG}"
              livenessProbe:
                # Give analyzer specified seconds to compute results, kill
                # stack producer so the main process reports scored results.
                exec:
                  command:
                    - python3
                    - liveness.py
                failureThreshold: 1
                initialDelaySeconds: "${THOTH_ADVISER_TIMEOUT_SECONDS}"
                # Give main process some time to finish scoring and submit results.
                timeoutSeconds: 300
              env:
                - name: THOTH_LOG_ADVISER
                  value: "${THOTH_LOG_ADVISER}"
                - name: THOTH_ADVISER_OUTPUT
                  value: "${THOTH_ADVISER_OUTPUT}"
                - name: THOTH_ADVISER_COUNT
                  value: "${THOTH_ADVISER_COUNT}"
                - name: THOTH_ADVISER_LIMIT
                  value: "${THOTH_ADVISER_LIMIT}"
                - name: THOTH_ADVISER_REQUIREMENTS
                  value: "${THOTH_ADVISER_REQUIREMENTS}"
                - name: THOTH_ADVISER_REQUIREMENTS_LOCKED
                  value: "${THOTH_ADVISER_REQUIREMENTS_LOCKED}"
                - name: THOTH_ADVISER_REQUIREMENTS_FORMAT
                  value: "${THOTH_ADVISER_REQUIREMENTS_FORMAT}"
                - name: THOTH_ADVISER_RECOMMENDATION_TYPE
                  value: "${THOTH_ADVISER_RECOMMENDATION_TYPE}"
                - name: THOTH_ADVISER_RUNTIME_ENVIRONMENT
                  value: "${THOTH_ADVISER_RUNTIME_ENVIRONMENT}"
                - name: THOTH_ADVISER_SUBCOMMAND
                  value: "advise"
                - name: THOTH_ADVISER_LIMIT_LATEST_VERSIONS
                  value: "${THOTH_ADVISER_LIMIT_LATEST_VERSIONS}"
                - name: ISIS_API_URL
                  valueFrom:
                    configMapKeyRef:
                      key: isis-api-url
                      name: thoth
                - name: PROMETHEUS_PUSHGATEWAY_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: prometheus-pushgateway-host
                      name: thoth
                - name: PROMETHEUS_PUSHGATEWAY_PORT
                  valueFrom:
                    configMapKeyRef:
                      name: thoth
                      key: prometheus-pushgateway-port
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
              resources:
                limits:
                  memory: "512Mi"
                  cpu: "500m"
                requests:
                  memory: "512Mi"
                  cpu: "500m"
